const contractAddress = "0xc95738d0699B8c825748A47bCF64F4893FD756f9"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "¡¡Bienvenido a la colección de DiscoMacaws!!🦜🦜";
const welcome_h2 = "Conecta tu cartera de Metamask para iniciar 🦊";
const welcome_p = 'Tienda virtual de origen colombiano cuyo principal objetivo es generar arte virtual que será utilizado para renovar la boletería de discotecas y eventos. Cada NFT en nuestra tienda presenta un guacamayo que tiene accesorios característicos de nuestras regiones. Un porcentaje de las ganancias será donado a fundaciones que velan por la conservación del ecosistema amazónico que alberga guacamayos y muchas otras especies naturales que necesitan ser preservadas';
const h1_presale_coming_soon = "¡¡Drop de NFTs muy pronto!!🎉";
const h1_presale_mint = "¡¡Preventa de minado muy pronto!!";
const h1_public_mint = "¡¡Minado público abierto!!🎉🎉";
const h2_presale_coming_soon = "Cuenta regresiva de minado de preventa ⏰";
const h2_presale_mint = "Cuenta regresiva de minado público ⏰";
const p_presale_coming_soon = "Estamos trabajando para actualizar la colección. Queda atento a los próximos cambios!";
const p_presale_mint_not_whitelisted = "No has sido añadido a la Whitelist aún 😢";
const p_presale_mint_whitelisted = "¡Estás dentro de la whitelist! Ya puedes minar en la preventa 🎉";
const p_presale_mint_already_minted = "Ya has reclamado tu minado por ser miembro de la Whitelist. ¡Muchas gracias! ⛏🎉";
const p_public_mint = "No es necesario que estés en la Whitelist, ¡La colección pública ha sido abierta! 🎉";
const button_presale_coming_soon = "Entra a la Whitelist 📜";
const button_presale_mint_whitelisted = "Has el minado de tu NFT ⛏";
const button_presale_mint_not_whitelisted = "NEcesitas entrar a la Whitelist 📜";
const button_presale_already_minted = "¡¡Unete a la comunidad 👊!!";
const button_public_mint = "¡Mina tu NFT! ⛏";
const mint_failed = "El minado ha fallado.😢 Por favor, intenta de nuevo.";
